### ISSUE TITLE
Create a newsletter page

### ISSUE THREAD

**Issue by gianarb** [vim-php/vim-php.github.com#11]
Mailchimp provides this feed to stay in touch with the newsletter that you send.
http://us2.campaign-archive2.com/feed?u=03581a38fd820a06b0898c802&id=f41c69197d

we are interested to have a new page with a form, a slogan to convince people to subscribe and also a list of all newsletters that we sent.

**Comment by nitishkd** [comment]
Hi, I would like to claim this issue. Although i do not have very much exp in web dev but i would like to give it a shot.

**Comment by gianarb** [comment]
Thanks @nitishkd . No problem you can start and create a PR. We can proceed together if you have some trouble :)

**Comment by themaxsandelin** [comment]
Is this issue still unresolved? :)

**Comment by gianarb** [comment]
hello @themaxsandelin yes @nitishkd never come back :D

**Comment by themaxsandelin** [comment]
@gianarb That's a bummer. I could take this on if you'd like :)

**Comment by nitishkd** [comment]
@gianarb Sorry, can devote time right now because of ICPC. Apologies.

**Comment by gianarb** [comment]
No problem @nitishkd ! @themaxsandelin  if you like go!

**Comment by themaxsandelin** [comment]
@gianarb I'll have a look in the morning :)

**Comment by gianarb** [comment]
Thanks!

**Comment by themaxsandelin** [comment]
@gianarb I've taken a look but I won't have time for a while, so please pass it along to anyone open to taking it on. Will check back when I have more time :)

**Comment by gianarb** [comment]
Thanks
